### ISSUE TITLE
Defaults and other minor style bits

### ISSUE THREAD

**Issue by darribas** [alan-turing-institute/demoland-web#15]
Opening a new issue to report and track progress on a bunch of very minor issues I've come across while using the tool:

- [ ] "Air quality" --> "Air pollution" (it's more aligned with the scale and sign of the data (i.e., higher numbers, more pollution, not more quality)
- [ ] Default on landing should probably be Land Use, as it provides the more comprehensive overview of what the tool provides (with the indicator overview on the side)
- [ ] Default view when a comparison is set up should be the difference map, not one of the two maps being compared (this is more aligned with the user seeing a change in the map that shows the comparison when they click on "Compare with"

cc' @yongrenjie , @martinfleis , @ciupava

**Comment by yongrenjie** [comment]
ref. #16
