### ISSUE TITLE
Safari display is bugged.

### ISSUE THREAD

**Issue by yongrenjie** [alan-turing-institute/demoland-web#2]
via https://github.com/alan-turing-institute/demoland-web/pull/1#issuecomment-1549154399

**Comment by yongrenjie** [comment]
Actually, I could reproduce this issue 2 hours ago, but now that I've sat down to try to investigate, it shows up correctly.

@martinfleis Could I trouble you to check again?

**Comment by martinfleis** [comment]
Looks fine on my side as well. Self-fixing bugs are the best!

**Comment by yongrenjie** [comment]
Hmm, actually, I can reproduce this (Safari 16.4, macOS 13.3.1(a)) 😕

1. Quit Safari entirely
2. Reopen Safari and navigate to the website https://alan-turing-institute.github.io/demoland-web
3. Map appears bugged
4. Refresh the page and it goes away. The 'fix' persists as long as Safari isn't closed.

Neither Firefox (113.0.1) nor Chrome (113.0.5672.126) have this issue, only Safari.

There's another specific set of conditions I can reproduce this under:

1. Set `main` css to `height: 100%; width: 100%`, force refresh the page (cmd-shift-r).
6. The map will disappear because the parent container's height is calculated to be 0px.
7. Change to `height: 100vh, 100vw` and let Vite redraw the page. The map then reappears, but with a height of 300px.
8. Force refreshing causes the map to be correctly resized.

The 300px seems to be a 'default' height of mapbox/maplibre which arises when the height of the parent div can't be calculated correctly. Since this isn't an issue when force refreshing (step 4) it's possible that this is to do with the Vite HMR - in step 3 possibly the map calculation is being done before the height has been recalculated.

https://github.com/mapbox/mapbox-gl-js/issues/3265
