### ISSUE TITLE
try showing accessibility as log

### ISSUE THREAD

**Issue by martinfleis** [alan-turing-institute/demoland-web#26]
Accessibilities are super skewed distributions. it may be worth trying to show them as log(x) instead of x. I guess that it would show more information and since we're using an index anyway, it shouldn't matter much.

**Comment by yongrenjie** [comment]
Some comparisons:

## Option 1 — just linear scaling to 0->100 (what we're doing now)

<img width="836" alt="job" src="https://github.com/alan-turing-institute/demoland-web/assets/22414895/dd906b3d-7078-46c4-8f8d-b59435f50a36">
<img width="836" alt="green" src="https://github.com/alan-turing-institute/demoland-web/assets/22414895/9af49ec5-9a39-4ae5-aef6-5437b43b69a6">

## Option 2 — log2(val + 1)

<img width="836" alt="job_log2p" src="https://github.com/alan-turing-institute/demoland-web/assets/22414895/be1bc5f6-5685-4226-894e-cb9d56821a24">
<img width="836" alt="green_log2p" src="https://github.com/alan-turing-institute/demoland-web/assets/22414895/0be5bb63-4833-4ec1-840b-5269b6eef94f">

## Option 3 — asinh(val/2) / log(2) (taken from [R's `scales::pseudo_log_trans`](https://scales.r-lib.org/reference/log_trans.html))

<img width="836" alt="job_pseudolog" src="https://github.com/alan-turing-institute/demoland-web/assets/22414895/d305095c-9363-4cb0-80d9-404c7286571b">
<img width="836" alt="green_pseudolog" src="https://github.com/alan-turing-institute/demoland-web/assets/22414895/8d6e3ab5-b278-4c1f-828b-5ef90fe8c1be">

**Comment by martinfleis** [comment]
Hmm, that is probably not better. Thanks for trying it though!

**Comment by yongrenjie** [comment]
I could get some nicer distributions by massaging it a bit. Here's job accessibility as `log2(val + 100)` and greenspace as `log2(val + 1000)`:

<img width="836" alt="job_log2p100" src="https://github.com/alan-turing-institute/demoland-web/assets/22414895/4c1690d5-22c5-4083-bb50-1eb11d76db9b">

<img width="836" alt="green_log2p1000" src="https://github.com/alan-turing-institute/demoland-web/assets/22414895/299fcbfc-3c93-4031-ab1d-e71327445179">

**Comment by martinfleis** [comment]
That looks reasonable. The only issue is that the people may perceive a number 25 in the legend as half of 50, which is not the case anymore. Let's discuss it on Wednesday with others.

**Comment by martinfleis** [comment]
From discussion, things to consider:

- remove numbers
- we may leave it as it reflects reality that all jobs are in the centre

**Comment by yongrenjie** [comment]
My concern about removing numbers is that ... the user is shown numbers anyway, not just in the chart, but also in the map popups.

If the chart doesn't indicate the range of values we're covering, the number then becomes somewhat confusing as it's not clear whether a '20' is good or bad (for example).

A middle option might be to just put two ticks on the chart at the min (0) and max (100) values?

**Comment by yongrenjie** [comment]
Probably not happening, we can revisit the discussion here if necessary
