### ISSUE TITLE
tell the user what's going on with scenario boundary

### ISSUE THREAD

**Issue by yongrenjie** [alan-turing-institute/demoland-web#36]
Was thinking of a popup when hovering over the boundary LineString, but need to check how workable this is (and whether it would interfere with the existing hover behaviour).

Alternatively, we could place a map legend

**Comment by martinfleis** [comment]
It's currently mentioned in the welcome screen draft.

**Comment by yongrenjie** [comment]
Closed via https://github.com/alan-turing-institute/demoland-web/commit/e60ea025a93d14841e260baf611ddcbd3dfa14bc and https://github.com/alan-turing-institute/demoland-web/commit/e2d13f61cf8a16632794220859f74a56a6367d1c
