### ISSUE TITLE
move "show welcome screen again"

### ISSUE THREAD

**Issue by martinfleis** [alan-turing-institute/demoland-web#37]
Can we move the "show welcome screen again" button to bottom left corner and hide under some kind of an icon with question mark? It feels weird in its current spot.

**Comment by yongrenjie** [comment]
I stuck it next to the first paragraph of text for now, as I think it's a bit more noticeable there

<img width="299" alt="Screenshot 2023-06-27 at 17 37 26" src="https://github.com/alan-turing-institute/demoland-web/assets/22414895/694a0d0f-20ac-421f-bcb7-2a2ffa013e4c">

**Comment by martinfleis** [comment]
Looks good!
