### ISSUE TITLE
Scrollbar behaviour changes depending on macOS settings (!!!)

### ISSUE THREAD

**Issue by yongrenjie** [alan-turing-institute/demoland-web#43]
<img width="700" alt="Screenshot 2023-07-06 at 23 13 48" src="https://github.com/alan-turing-institute/demoland-web/assets/22414895/f6f7784d-fedf-4cca-9a15-7f726864e4d8">

On my work laptop this is set to 'Automatically based on mouse or trackpad', but at home it's 'Always', and who knows what it is on a PC... this leads to content being reflowed when the vertical scrollbar appears/disappears

The solution seems to be to use the `scrollbar-gutter` CSS property.

**Comment by yongrenjie** [comment]
`scrollbar-gutter: stable` works, but unfortunately this destroys the rounded borders... not really sure how to work around that.

**Comment by martinfleis** [comment]
What exactly does this mean?

**Comment by martinfleis** [comment]
I mean, what is the issue here?

**Comment by yongrenjie** [comment]
Whoops, I forgot to add a video. Here it is:

# Intended behaviour with macOS scrollbars set to 'Automatically based on mouse or trackpad'

Here the scrollbars which appear are 'overlay scrollbars', so they don't occupy extra space.

https://github.com/alan-turing-institute/demoland-web/assets/22414895/27895baa-ef89-4149-a666-e1f7d7b0de43

# Unintended behaviour with macOS scrollbars set to 'Always'

The scrollbars in this case take up width, and causes the 'jumping' effect seen below:

https://github.com/alan-turing-institute/demoland-web/assets/22414895/b66ca646-6b64-44e2-aca5-c52e7b5eb203

**Comment by martinfleis** [comment]
and do you have an illustration of this?

> scrollbar-gutter: stable works, but unfortunately this destroys the rounded borders... not really sure how to work around that.

**Comment by yongrenjie** [comment]
Not really, because I've since found a better solution - there's a [JavaScript plugin which forces the use of overlay scrollbars](https://kingsora.github.io/OverlayScrollbars/).

Basically what happens with scrollbar-gutter, though, is that it allocates some width in the div to the scrollbar and makes it permanently visible. (the div width needs to be increased a bit to compensate) Unfortunately, the scrollbars that it generates are rectangular, so the top-right and bottom-right corners of the div no longer get rounded corners.
