### ISSUE TITLE
diffs between two scenarios

### ISSUE THREAD

**Issue by yongrenjie** [alan-turing-institute/demoland-web#44]
right now the black outline shows differences between scenario X and baseline.

ideally we would like to have it show the differences between the two scenarios being compared!

**Comment by yongrenjie** [comment]
right now it shows both differences, i.e. (scenarioX - baseline) + (scenarioY - baseline)

**Comment by yongrenjie** [comment]
http://turfjs.org/docs/#union

**Comment by yongrenjie** [comment]
Okay. This is almost correct except that when we set 

```
scenario4.loc[scenario4.index.isin(brownfield_OAs.geo_code), "signature_type"] = 11
```

some of the original OAs already have signature type 11, so we might not (?) want to highlight that.

Also, it's a bit odd comparing scen7 and scen3 and having an outline, but not being able to see any differences in land use (the difference is in greenspace allocation). But that's an issue for another day.

**Comment by martinfleis** [comment]
> some of the original OAs already have signature type 11, so we might not (?) want to highlight that.

I still would on the basis of _this is the area of change_ no matter the existing situation.
